services:
  palui:
    container_name: palui
    image: ghcr.io/musclepr/palui:latest
    build:
      context: ..
    environment:
      - "TZ=${TZ:-Etc/UTC}"
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "DOCKER_GID=${DOCKER_GID:-}"
      - "NEXTAUTH_URL=http://localhost:8080${NEXT_PUBLIC_BASE_PATH:-/palui}"
    volumes:
      - ./server:/server
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:3000"
