name: ${PROJECT:-dev}
services:
  palui:
    container_name: ${COMPOSE_PROJECT_NAME}-palui
    image: ghcr.io/musclepr/palui:latest
    environment:
      - "TZ=${TZ:-Etc/UTC}"
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "DOCKER_GID=${DOCKER_GID:-}"
      - "NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH:-/palui}"
      - "NEXTAUTH_URL=http://localhost:8080${NEXT_PUBLIC_BASE_PATH:-/palui}"
      - "COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}_pal"
    volumes:
      - ./server:/server
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:3000"
